<?php
if (!defined("PJ_HOST")) define("PJ_HOST", "localhost");
if (!defined("PJ_USER")) define("PJ_USER", "u780534123_michalipka");
if (!defined("PJ_PASS")) define("PJ_PASS", "Wikaryjka22#");
if (!defined("PJ_DB")) define("PJ_DB", "u780534123_booking");
if (!defined("PJ_PREFIX")) define("PJ_PREFIX", "");
if (!defined("PJ_INSTALL_FOLDER")) define("PJ_INSTALL_FOLDER", "/script/");
if (!defined("PJ_INSTALL_PATH")) define("PJ_INSTALL_PATH", "/home/u780534123/domains/gabriela-salon.pl/public_html/script/");
if (!defined("PJ_INSTALL_URL")) define("PJ_INSTALL_URL", "https://gabriela-salon.pl/script/");
if (!defined("PJ_SALT")) define("PJ_SALT", "QXVAF0J6");
if (!defined("PJ_INSTALLATION")) define("PJ_INSTALLATION", "MTIzMzU5MjQwOTcyNjk3ODA5MTY3MTg0NjU1MTA0MjAyMDAyMzU5NTc1MTk3ODI5MjM4NjgyNzM3MTE1NTk4OTYzNDUzMDM0MDU5ODQxMzY2NzE3MTEwMjQwNDk1MTEyMDkzOSA2NTYxNDUyMzMyMjQ5OTUzMDUyNzQ4OTcxOTEwNDgwNDA3MDQ1NjUyMDI1ODgxNjM0NTgxMjI0Mjk1ODc4NDI3NzIzMzE1OTkzNzM1MDMxMDQxNjQ2Nzc5NjUzNjg1NDkyMDggODEyMjQ5ODc4NTI1MTYyNDEwNTc2Njg1NDc0ODMyMjA5MTY3MDYxNjM1NDIwMzA1NzMxMzU1NzQ3MDQ2ODU3NDE1Mzk2MDYwNzIyNDI1MjMxMjI3MDI3OTc5NDgyNjA3MTY2IDEzNDM3MTAzNDIzNDY3NzQxMjMzMDM0NTEwOTYyMTUzMTY5MTA0ODA2MDAwNTUwNTQyMTQ5MDUwNzQ3ODgyMjM1OTI3MjE4MzUxNTg3MjA2MTcxNzAwNjMyNTM4MzgyMTIxNjAgMTI2Mjc5NjA5MTczNTEzMjM1MzUyNzgwNzk1MjY2MzQwNjc3Mjg4NDQxODA2MzY2ODI1MDE4MDM2MDYyMTUzODUwOTczMjA2MDY1Mjg5ODYzNDUyMTcyNDIzODgyMDIyNTE2NCAxMzIzMTMyNTEyMzkyMDczODM1MDYzODcwNTk0MjE0MDYyOTY4NzgxNjQ2ODA1ODY3ODMzNjU5ODUzNTg2Mzc0OTA4MTQwNjcwMjgxMjk4NjkwMjY0NjEyNTI2NzcyNjc3OTM5");
?>